config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'sign_up' => 'static_pages#sign_up'
  post 'sessions/create' => 'sessions#create'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def sign_up

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item_form.html.erb
<%= simple_form_for(item) do |f| %>
    <%= f.input :url, as: :url, placeholder: 'Add an item to the sack' %>
    <%= f.submit %>
<% end %>

app/views/items/_search_form.html.erb
<section class="margin-bottom">
    <header class="column_5 margin-bottom offset_1 align right">
        <h1 class="text bold">start picking</h1>
        <h5><strong class="color theme"><%= Item.count %></strong> items in your sack</h5>
    </header>
    <%= form_tag items_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: 'Search items in the sack' %>
    <% end %>
</section>
<hr>

app/views/items/_search_results.html.erb
<section>
    <p class="align right margin-bottom"><small>Your search returned </small><strong><%= items.size %></strong><small> hits in your sack</small></p>
    <% items.each do |item| %>
        <article class="bck light margin-bottom padding">
            <header>
            </header>
            <div>
                    <%= link_to item.title,
                        item.url,
                        target: 'blank',
                        class: 'text underline color darkest bold' %>:
                <small><%= item.description %></small>
                <%= link_to 'Click to edit', edit_item_path(item), class: 'on-right', id: 'toggle-edit-form' %>
            </div>
        </article>
    <% end %>
</section>

app/views/items/_sidebar.html.erb
<aside class="column_3 margin-top">
    <section>
        <header class="margin align center">
            <%= image_tag 'sack.png', width: '200' %>
        </header>
         <p class="notice"><%= notice %></p>
         <%= render partial: 'item_form', locals: { item: @item } %>
         <%= render partial: 'success_modal' %>
    </section>  
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sack</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar">
        <ul class="nav-list">
            <li class="nav-item"><%= link_to "Sign in", '#' %></li>
            <li class="nav-item"><%= link_to "Sign up", sign_up_path %></li>
        </ul>
    </nav>
    <%= yield %>

</body>
</html>

app/views/saks/_edit_item_form.html.erb
<div id="edit-item-form">
    <%= simple_form_for(item) do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.submit %>
<% end %>
</div>

app/views/static_pages/home.html.erb
<div class="container">
    <div class="logo_container center">
        <%= image_tag 'logo-sack.svg', class: 'home_logo' %>
        <h2 class="claim">Infoxication sucks!</h2>
    </div>
</div>

app/views/static_pages/sign_up.html.erb
<%= link_to "Sign up with Google", action: "create", :controller => "sessions" %>